// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHP-X7rt1zbCuxaBcEo1Jxp9BeEIkmxU',
    appId: '1:581612918466:android:969c28548b823a2e668d5b',
    messagingSenderId: '581612918466',
    projectId: 'hotel-booking-42680',
    storageBucket: 'hotel-booking-42680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKbMBrypBbupN0ctatj0Qvyg2kwoWEbEg',
    appId: '1:581612918466:ios:75c898dc1ba077a0668d5b',
    messagingSenderId: '581612918466',
    projectId: 'hotel-booking-42680',
    storageBucket: 'hotel-booking-42680.firebasestorage.app',
    iosBundleId: 'com.akillisletme.hotelbooking.flutterHotelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKbMBrypBbupN0ctatj0Qvyg2kwoWEbEg',
    appId: '1:581612918466:ios:75c898dc1ba077a0668d5b',
    messagingSenderId: '581612918466',
    projectId: 'hotel-booking-42680',
    storageBucket: 'hotel-booking-42680.firebasestorage.app',
    iosBundleId: 'com.akillisletme.hotelbooking.flutterHotelBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSwrvuZH5P1rU0etkWBh7qb-9SiOmJAB8',
    appId: '1:581612918466:web:ddf0721fd8ff388a668d5b',
    messagingSenderId: '581612918466',
    projectId: 'hotel-booking-42680',
    authDomain: 'hotel-booking-42680.firebaseapp.com',
    storageBucket: 'hotel-booking-42680.firebasestorage.app',
  );
}
