include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    sort_pub_dependencies: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore

linter:
  rules:
    
    



